=== dpukhkaiev/BRISE2/main-node/Resources/schema/experiment.schema.json
{
    "$id": "http://brise.com/experiment.schema.json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "General": {
            "type": "object",
            "properties": {
                "isMinimizationExperiment": {
                    "type": "boolean"
                }
            },
            "required": [
                "isMinimizationExperiment"
            ]
        },
        "DomainDescription": {
            "type": "object",
            "properties": {
                "HyperparameterNames": {
                    "type": "array",
                    "items": [{
                            "type": "string"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "DataFile": {
                    "type": "string"
                },
                "DefaultConfigurationHandler": {
                    "type": "string"
                }
            },
            "required": [
                "HyperparameterNames",
                "DataFile"
            ]
        },
        "SelectionAlgorithm": {
            "anyOf": [{
                "$ref": "./selection/schema/sel_algorithm.schema.json#/definitions/SobolSequence"
            },
            {
                "$ref": "./selection/schema/sel_algorithm.schema.json#/definitions/ConfigSpaceSelector"
            }]
        },
        "TaskConfiguration": {
            "type": "object",
            "properties": {
                "TaskName": {
                    "type": "string"
                },
                "Scenario": {
                    "type": "object"
                },
                "TaskParameters": {
                    "type": "array",
                    "items": [{
                            "type": "string"
                        },
                        {
                            "type": "string"
                        }
                    ]
                },
                "ResultStructure": {
                    "type": "array",
                    "items": [{
                        "type": "string"
                    }]
                },
                "ResultDataTypes": {
                    "type": "array",
                    "items": [{
                        "type": "string"
                    }]
                },
                "ExpectedValuesRange": {
                    "type": "array",
                    "items": [{
                        "type": "array",
                        "items":[{
                            "type":"number"
                        }]
                    }]
                },
                "ResultPriorities": {
                    "type": "array",
                    "items": [{
                        "type": "integer",
                        "minimum": 0
                    }]
                },
                "MaxTimeToRunTask": {
                    "type": "number",
                    "minimum": 0,
                    "exclusiveMinimum": true
                }
            },
            "required": [
                "TaskName",
                "Scenario",
                "TaskParameters",
                "ResultStructure",
                "ResultDataTypes",
                "ExpectedValuesRange"
            ]
        },
        "OutliersDetection":{
            "$ref": "./outliers/schema/outlier_detector.schema.json#/definitions/OutliersDetection"
        },
        "Repeater": {
            "description": "Parameters related to Configuration evaluation accuracy.",
            "anyOf": [
                {
                    "$ref": "./repeater/schema/repeater.schema.json#/definitions/Default"
                },
                {
                    "$ref": "./repeater/schema/repeater.schema.json#/definitions/Student"
                }
            ]
        },
        "ModelConfiguration": {
            "description": "Configuration related to the prediction model creation process.",
            "anyOf": [
                {
                    "$ref": "./model/schema/model.schema.json#/definitions/BayesianOptimization"
                },
                {
                    "$ref": "./model/schema/model.schema.json#/definitions/Regression"
                }
            ]
        },
        "StopConditionTriggerLogic": {
            "type": "object",
            "properties": {
                "Expression": {
                    "type": "string"
                },
                "InspectionParameters":{
                    "type": "object",
                    "properties": {
                        "RepetitionPeriod": {
                            "type": "number",
                            "minimum": 0,
                            "exclusiveMinimum": true
                        },
                        "TimeUnit": {
                            "type": "string",
                            "enum": ["seconds","minutes","hours","days"]
                        }
                    }
                }
            },
            "required": [
                "Expression"
            ]
        },
        "StopCondition": {
            "$ref": "./stop_condition/schema/stop_condition.schema.json#/definitions/StopCondition"
        }
    },
    "required": [
        "General",
        "DomainDescription",
        "SelectionAlgorithm",
        "TaskConfiguration",
        "OutliersDetection",
        "Repeater",
        "ModelConfiguration",
        "StopCondition"
    ]
}

=== dpukhkaiev/BRISE2/main-node/Resources/spark/SparkExperiment.json
{
  "General":{
    "isMinimizationExperiment"  : true
  },
  "DomainDescription":{
    "HyperparameterNames"      : ["master", "deploy_mode", "driver_memory", "num_executors", "executor_memory", "executor_cores", "spark.python.worker.reuse", "spark.reducer.maxSizeInFlight", "spark.shuffle.compress", "spark.shuffle.file.buffer", "spark.broadcast.compress", "spark.memory.fraction", "spark.memory.storageFraction", "spark.dynamicAllocation.enabled", "spark.shuffle.service.enabled"],
    "DataFile"          : "./Resources/spark/SparkExperimentData.json"
  },
  "SelectionAlgorithm":{
    "SelectionType"     : "SobolSequence"
  },
  "TaskConfiguration":{
    "TaskName"          : "spark",
    "Scenario":{
      "ws_file": ""
    },
    "TaskParameters"   : ["master", "deploy_mode", "driver_memory", "num_executors", "executor_memory", "executor_cores", "spark.python.worker.reuse", "spark.reducer.maxSizeInFlight", "spark.shuffle.compress", "spark.shuffle.file.buffer", "spark.broadcast.compress", "spark.memory.fraction", "spark.memory.storageFraction", "spark.dynamicAllocation.enabled", "spark.shuffle.service.enabled"],
    "ResultStructure"   : ["time"],
    "ResultDataTypes"  : ["float"],
    "ExpectedValuesRange": [[0, "inf"]]
  },
  "OutliersDetection":[
    {
      "Type": "Dixon",
      "Parameters": {
        "MinActiveNumberOfTasks": 3,
        "MaxActiveNumberOfTasks": 30
      }
    },
    {
      "Type": "Chauvenet",
      "Parameters": {
        "MinActiveNumberOfTasks": 3,
        "MaxActiveNumberOfTasks": 10000
      }
    },
    {
      "Type": "MAD",
      "Parameters": {
        "MinActiveNumberOfTasks": 3,
        "MaxActiveNumberOfTasks": 10000
      }
    },
    {
      "Type": "Grubbs",
      "Parameters": {
        "MinActiveNumberOfTasks": 3,
        "MaxActiveNumberOfTasks": 10000
      }
    },
    {
      "Type": "Quartiles",
      "Parameters": {
        "MinActiveNumberOfTasks": 3,
        "MaxActiveNumberOfTasks": 10000
      }
    }
  ],
  "Repeater":{
    "Type": "default",
    "Parameters": {
      "MaxFailedTasksPerConfiguration": 5,
      "MaxTasksPerConfiguration": 1
    }
  },
  "ModelConfiguration":{
    "SamplingSize": 96,
    "ModelType"         : "BO"
  },
  "StopCondition":[
    {
      "Type": "Default",
      "Parameters": {
        "MaxConfigs": 100000
      }
    },
    {
      "Type": "ImprovementBased",
      "Parameters": {
        "MaxConfigsWithoutImprovement": 5
      }
    },
    {
      "Type": "Guaranteed",
      "Parameters": {      }
    },
    {
      "Type": "TimeBased",
      "Parameters": {
        "MaxRunTime": 10,
        "TimeUnit": "minutes"
      }
    },
    {
      "Type": "BadConfigurationBased",
      "Parameters": {
        "MaxBadConfigurations": 10
      }
    }
  ]
}
